# Generated by Django 6.0.7 on 2026-08-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doselog',
            name='skip_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doselog',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='afternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='medication',
            name='evening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medication',
            name='morning',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='night',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='remaining_tablets',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='medication',
            name='timing_instruction',
            field=models.CharField(default='after_food', max_length=50),
        ),
        migrations.AddField(
            model_name='medication',
            name='total_tablets',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='doselog',
            name='status',
            field=models.CharField(choices=[('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped'), ('snoozed', 'Snoozed')], max_length=10),
        ),
    ]
