# Generated by Django 6.0.7 on 2026-08-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_doselog_skip_reason_doselog_snoozed_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='confidence_score',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='prescriptions/pdf/'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('processed', 'Processed'), ('review_required', 'Review Required'), ('failed', 'Failed')], default='processed', max_length=20),
        ),
    ]
