# Generated by Django 6.0.7 on 2026-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_prescription_confidence_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='elder_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='high_contrast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='large_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('kn', 'Kannada'), ('ta', 'Tamil'), ('te', 'Telugu'), ('ml', 'Malayalam')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reminder_repeat_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='speech_speed',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voice_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
