# Generated by Django 6.0.7 on 2026-08-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_appointment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='classification_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prescription',
            name='document_type',
            field=models.CharField(choices=[('prescription', 'Doctor Prescription'), ('blood_test', 'Blood Test Report'), ('urine_test', 'Urine Test Report'), ('ultrasound', 'Ultrasound Report'), ('xray', 'X-Ray Report'), ('mri', 'MRI Report'), ('ct_scan', 'CT Scan Report'), ('ecg', 'ECG Report'), ('discharge_summary', 'Discharge Summary'), ('vaccination', 'Vaccination Record'), ('medical_certificate', 'General Medical Certificate'), ('unknown', 'Unknown / Unrecognized')], default='prescription', max_length=30),
        ),
        migrations.AddField(
            model_name='prescription',
            name='ocr_confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
