# Generated by Django 6.0.7 on 2026-08-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_prescription_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='afternoon_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='evening_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='morning_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='night_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
