# Generated by Django 6.0.7 on 2026-08-11 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_medication_afternoon_time_medication_evening_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('reminder_date', models.DateField()),
                ('reminder_time', models.TimeField()),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('snoozed', 'Snoozed'), ('missed', 'Missed')], default='pending', max_length=10)),
                ('notification_sent', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=2)),
                ('retry_interval_minutes', models.IntegerField(default=15)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medication', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='core.medication')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='core.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reminder_date', 'reminder_time'],
                'indexes': [models.Index(fields=['status', 'reminder_date', 'reminder_time'], name='core_medici_status_f9402f_idx'), models.Index(fields=['user', 'reminder_date'], name='core_medici_user_id_8be72b_idx')],
                'unique_together': {('user', 'medication', 'reminder_date', 'reminder_time')},
            },
        ),
    ]
