# Generated by Django 6.0.7 on 2026-08-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_timezone_fcmdevice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinereminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('snoozed', 'Snoozed'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='pending', max_length=10),
        ),
    ]
